---
- hosts: testbed
  become: true 
  tasks:

    - name: install requests
      pip: 
        name: requests
    

    - name: install scipy
      pip: 
        name: scipy

    - name: example copying file with owner and permissions
      copy:
        src: watcher.py
        dest: /home/vagrant/watcher.py
        mode: 0644