---
- hosts: testbed
  become: true 
  tasks:
    # - name: install pip
    #   apt:
    #     name: python3-pip
    #     state: present
    #     update_cache: true

    # - name: install python dependencies
    #   pip: 
    #     name: sudo pip install requests, numpy, matplotlib

    - name: example copying file with owner and permissions
      copy:
        src: watcher.py
        dest: /home/vagrant/watcher.py
        mode: 0644