---
- hosts: testbed
  become: true
  tasks:
    - name: install stress
      apt:
        name: stress
        state: present
        update_cache: true

    - name: stress
      shell: while true; do stress --cpu 8 --timeout 5s; sleep 10; done